#![allow(non_upper_case_globals)]

use crate::attack::Move;
use crate::item::Item::Everstone;

/// All Pokeballs in the game
#[derive(Debug)]
pub enum Pokeball {
    PokeBall,
    GreatBall,
    UltraBall,
    MasterBall,
    SafariBall,
    FastBall,
    LevelBall,
    LureBall,
    HeavyBall,
    LoveBall,
    FriendBall,
    MoonBall,
    SportBall,
    NetBall,
    NestBall,
    RepeatBall,
    TimerBall,
    LuxuryBall,
    PremierBall,
    DiveBall,
    DuskBall,
    HealBall,
    QuickBall,
    CherishBall,
    ParkBall,
    DreamBall
}

/// All Evolution Stones in the game
#[derive(Debug)]
pub enum EvolutionStone {
    FireStone,
    WaterStone,
    ThunderStone,
    LeafStone,
    MoonStone,
    SunStone,
    ShinyStone,
    DuskStone,
    DawnStone,
    IceStone
}

/// All incenses in the game
#[derive(Debug)]
pub enum Incense {
    FullIncense,
    LaxIncense,
    LuckIncense,
    OddIncense,
    PureIncense,
    RockIncense,
    RoseIncense,
    SeaIncense,
    WaveIncense
}

/// All Evolution-inducing held items in the game
#[derive(Debug)]
pub enum EvolutionHeldItem {
    DeepSeaTooth,
    DeepSeaScale,
    DragonScale,
    DubiousDisk,
    Electirizer,
    KingsRock,
    Magmarizer,
    MetalCoat,
    OvalStone,
    PrismScale,
    Protector,
    RazorClaw,
    RazorFang,
    ReaperCloth,
    UpGrade
}

/// All berries in the game
#[derive(Debug)]
pub enum Berry {
    CheriBerry,
    ChestoBerry,
    PechaBerry,
    RawstBerry,
    AspearBerry,
    LeppaBerry,
    OranBerry,
    PersimBerry,
    LumBerry,
    SitrusBerry,
    FigyBerry,
    WikiBerry,
    MagoBerry,
    AguavBerry,
    IapapaBerry,
    RazzBerry,
    BlukBerry,
    NanabBerry,
    WepearBerry,
    PinapBerry,
    PomegBerry,
    KelpsyBerry,
    QualotBerry,
    HondewBerry,
    GrepaBerry,
    TamatoBerry,
    CornnBerry,
    MagostBerry,
    RabutaBerry,
    NomelBerry,
    SpelonBerry,
    PamtreBerry,
    WatmelBerry,
    DurinBerry,
    BelueBerry,
    OccaBerry,
    PasshoBerry,
    WacanBerry,
    RindoBerry,
    YacheBerry,
    ChopleBerry,
    KebiaBerry,
    ShucaBerry,
    CobaBerry,
    PayapaBerry,
    TangaBerry,
    ChartiBerry,
    KasibBerry,
    HabanBerry,
    ColburBerry,
    BabiriBerry,
    ChilanBerry,
    LiechiBerry,
    GanlonBerry,
    SalacBerry,
    PetayaBerry,
    ApicotBerry,
    LansatBerry,
    StarfBerry,
    EnigmaBerry,
    MicleBerry,
    CustapBerry,
    JabocaBerry,
    RowapBerry,
    RoseliBerry,
    KeeBerry,
    MarangaBerry
}

//region TMs and HMs
/// All TMs in the game, and their mappings
#[derive(Debug)]
pub enum TM {
    TM01, TM02, TM03, TM04, TM05, TM06, TM07, TM08, TM09, TM10, TM11, TM12, TM13, TM14, TM15, TM16, TM17, TM18, TM19, TM20, TM21, TM22, TM23, TM24, TM25, TM26, TM27, TM28, TM29, TM30, TM31, TM32, TM33, TM34, TM35, TM36, TM37, TM38, TM39, TM40, TM41, TM42, TM43, TM44, TM45, TM46, TM47, TM48, TM49, TM50, TM51, TM52, TM53, TM54, TM55, TM56, TM57, TM58, TM59, TM60, TM61, TM62, TM63, TM64, TM65, TM66, TM67, TM68, TM69, TM70, TM71, TM72, TM73, TM74, TM75, TM76, TM77, TM78, TM79, TM80, TM81, TM82, TM83, TM84, TM85, TM86, TM87, TM88, TM89, TM90, TM91, TM92, TM93, TM94, TM95, TM96, TM97
}
impl TM {
    pub fn get_move(&self) -> &Move {
        match self {
            TM::TM01 => &Move::HoneClaws,
            TM::TM02 => &Move::DragonClaw,
            TM::TM03 => &Move::Psyshock,
            TM::TM04 => &Move::CalmMind,
            TM::TM05 => &Move::Roar,
            TM::TM06 => &Move::Toxic,
            TM::TM07 => &Move::Hail,
            TM::TM08 => &Move::BulkUp,
            TM::TM09 => &Move::Venoshock,
            TM::TM10 => &Move::HiddenPower,
            TM::TM11 => &Move::SunnyDay,
            TM::TM12 => &Move::Taunt,
            TM::TM13 => &Move::IceBeam,
            TM::TM14 => &Move::Blizzard,
            TM::TM15 => &Move::HyperBeam,
            TM::TM16 => &Move::LightScreen,
            TM::TM17 => &Move::Protect,
            TM::TM18 => &Move::RainDance,
            TM::TM19 => &Move::Roost,
            TM::TM20 => &Move::Safeguard,
            TM::TM21 => &Move::Frustration,
            TM::TM22 => &Move::SolarBeam,
            TM::TM23 => &Move::SmackDown,
            TM::TM24 => &Move::Thunderbolt,
            TM::TM25 => &Move::Thunder,
            TM::TM26 => &Move::Earthquake,
            TM::TM27 => &Move::Return,
            TM::TM28 => &Move::Dig,
            TM::TM29 => &Move::Psychic,
            TM::TM30 => &Move::ShadowBall,
            TM::TM31 => &Move::BrickBreak,
            TM::TM32 => &Move::DoubleTeam,
            TM::TM33 => &Move::Reflect,
            TM::TM34 => &Move::SludgeWave,
            TM::TM35 => &Move::Flamethrower,
            TM::TM36 => &Move::SludgeBomb,
            TM::TM37 => &Move::Sandstorm,
            TM::TM38 => &Move::FireBlast,
            TM::TM39 => &Move::RockTomb,
            TM::TM40 => &Move::AerialAce,
            TM::TM41 => &Move::Torment,
            TM::TM42 => &Move::Facade,
            TM::TM43 => &Move::FlameCharge,
            TM::TM44 => &Move::Rest,
            TM::TM45 => &Move::Attract,
            TM::TM46 => &Move::Thief,
            TM::TM47 => &Move::LowSweep,
            TM::TM48 => &Move::Round,
            TM::TM49 => &Move::EchoedVoice,
            TM::TM50 => &Move::Overheat,
            TM::TM51 => &Move::SteelWing,
            TM::TM52 => &Move::FocusBlast,
            TM::TM53 => &Move::EnergyBall,
            TM::TM54 => &Move::FalseSwipe,
            TM::TM55 => &Move::Scald,
            TM::TM56 => &Move::Fling,
            TM::TM57 => &Move::ChargeBeam,
            TM::TM58 => &Move::SkyDrop,
            TM::TM59 => &Move::Incinerate,
            TM::TM60 => &Move::Quash,
            TM::TM61 => &Move::WillOWisp,
            TM::TM62 => &Move::Acrobatics,
            TM::TM63 => &Move::Embargo,
            TM::TM64 => &Move::Explosion,
            TM::TM65 => &Move::ShadowClaw,
            TM::TM66 => &Move::Payback,
            TM::TM67 => &Move::Retaliate,
            TM::TM68 => &Move::GigaImpact,
            TM::TM69 => &Move::RockPolish,
            TM::TM70 => &Move::Flash,
            TM::TM71 => &Move::StoneEdge,
            TM::TM72 => &Move::VoltSwitch,
            TM::TM73 => &Move::ThunderWave,
            TM::TM74 => &Move::GyroBall,
            TM::TM75 => &Move::SwordsDance,
            TM::TM76 => &Move::StruggleBug,
            TM::TM77 => &Move::PsychUp,
            TM::TM78 => &Move::Bulldoze,
            TM::TM79 => &Move::FrostBreath,
            TM::TM80 => &Move::RockSlide,
            TM::TM81 => &Move::XScissor,
            TM::TM82 => &Move::DragonTail,
            TM::TM83 => &Move::WorkUp,
            TM::TM84 => &Move::PoisonJab,
            TM::TM85 => &Move::DreamEater,
            TM::TM86 => &Move::GrassKnot,
            TM::TM87 => &Move::Swagger,
            TM::TM88 => &Move::SleepTalk,
            TM::TM89 => &Move::UTurn,
            TM::TM90 => &Move::Substitute,
            TM::TM91 => &Move::FlashCannon,
            TM::TM92 => &Move::TrickRoom,
            TM::TM93 => &Move::WildCharge,
            TM::TM94 => &Move::SecretPower,
            TM::TM95 => &Move::Snarl,
            TM::TM96 => &Move::NaturePower,
            TM::TM97 => &Move::DarkPulse
        }
    }
}

/// All HMs in the game, and their mappings
#[derive(Debug)]
pub enum HM {
    HM01, HM02, HM03, HM04, HM05, HM06, HM07, HM08
}
impl HM {
    pub fn get_move(&self) -> &Move {
        match self {
            HM::HM01 => &Move::Cut,
            HM::HM02 => &Move::Fly,
            HM::HM03 => &Move::Surf,
            HM::HM04 => &Move::Strength,
            HM::HM05 => &Move::Flash,
            HM::HM06 => &Move::RockSmash,
            HM::HM07 => &Move::Waterfall,
            HM::HM08 => &Move::Dive
        }
    }
}
//endregion

/// All Mail in the game
/// Messages are attached via the included String
#[derive(Debug)]
pub enum Mail {
    AirMail(String),
    BloomMail(String),
    BrickMail(String),
    BubbleMail(String),
    FlameMail(String),
    GrassMail(String),
    HeartMail(String),
    MosaicMail(String),
    SnowMail(String),
    SpaceMail(String),
    SteelMail(String),
    TunnelMail(String)
}

/// All Key items in the game
#[derive(Debug)]
pub enum KeyItem {

}

/// All Items in the game
/// Items from the above lists are wrapped, so they can still be considered items
#[derive(Debug)]
pub enum Item {
    Pokeball(Pokeball),
    Stone(EvolutionStone),
    Everstone,
    Incense(Incense),
    EvolutionHeldItem(EvolutionHeldItem),
    Berry(Berry),
    TM(TM),
    HM(HM),
    Mail(Mail),
    KeyItem(KeyItem),
    // Use Items
    // Health
    Potion, SuperPotion, HyperPotion, MaxPotion,
    BerryJuice, EnergyRoot, EnergyPowder, FreshWater, Lemonade, MoomooMilk, RageCandyBar,
    SacredAsh, ShellBell, SodaPop, SweetHeart, RevivalHerb,
    // Status
    Antidote, Awakening, BurnHeal, FullHeal, FullRestore, IceHeal, ParalyzeHeal, Revive, MaxRevive,
    LavaCookie, MentalHerb, OldGateau, Casteliacone,
    // PP
    Ether, MaxEther, Elixir, MaxElixir, PPUp, PPMax,
    // Stats
    HPUp, Protein, Iron, Calcium, Zinc, Carbos,
    // Held Items
    ShockDrive, BurnDrive, ChillDrive, DouseDrive,
    PowerAnklet, PowerBand, PowerBelt, PowerBracer, PowerLens, PowerWeight,
    ExpShare, LuckyEgg,
    DracoPlate, DreadPlate, EarthPlate, FistPlate, FlamePlate, IciclePlate, InsectPlate, IronPlate,
    MeadowPlate, MindPlate, PixiePlate, SkyPlate, SplashPlate, SpookyPlate, StonePlate, ToxicPlate, ZapPlate,
    Eviolite, Leek, LightBall, LuckyPunch, MetalPowder, QuickPowder, SoulDew, ThickClub,
    BlackBelt, BlackGlasses, Charcoal, DragonFang, HardStone, Magnet, MetalCoat, MiracleSeed, MysticWater,
    NeverMeltIce, PoisonBarb, SharpBeak, SilkScarf, SilverPowder, SoftSand, SpellTag, TwistedSpoon,
    AdamantOrb, LustrousOrb, GriseousOrb,
    BlueScarf, GreenScarf, PinkScarf, RedScarf, YellowScarf,
    SootheBell, CleanseTag, ChoiceBand, ChoiceScarf, ChoiceSpecs, BlackSludge, LifeOrb, RockyHelmet, StickyBarb,
    GripClaw, LightClay, TerrainExtender, AssaultVest, FlameOrb, IronBall, LaggingTail, MachoBrace,
    RingTarget, ToxicOrb, Leftovers, AbsorbBulb, CellBattery, EjectButton, LuminousMoss,
    Snowball, WeaknessPolicy, WideLens
}

#[derive(Debug)]
pub enum Pocket {
    Items,
    Medicine,
    PokeBalls,
    TMsAndHMs,
    Berries,
    Mail,
    BattleItems,
    KeyItems
}

#[derive(Debug)]
pub struct ItemData {
    pub id: u16,
    pub cost: u16,
    pub pocket: Pocket,
    pub countable: bool,
    pub consumable: bool,
    pub holdable: bool,
    pub battle_usable: bool,
    pub overworld_usable: bool
}

//region Item constants
impl Item {
    pub fn data(&self) -> &'static ItemData {
        match self {
            Item::Pokeball(Pokeball::PokeBall) => &PokeBall,
            Item::Pokeball(Pokeball::GreatBall) => &GreatBall,
            Item::Pokeball(Pokeball::UltraBall) => &UltraBall,
            Item::Pokeball(Pokeball::MasterBall) => &MasterBall,
            Item::Pokeball(Pokeball::SafariBall) => &SafariBall,
            Item::Pokeball(Pokeball::FastBall) => &FastBall,
            Item::Pokeball(Pokeball::LevelBall) => &LevelBall,
            Item::Pokeball(Pokeball::LureBall) => &LureBall,
            Item::Pokeball(Pokeball::HeavyBall) => &HeavyBall,
            Item::Pokeball(Pokeball::LoveBall) => &LoveBall,
            Item::Pokeball(Pokeball::FriendBall) => &FriendBall,
            Item::Pokeball(Pokeball::MoonBall) => &MoonBall,
            Item::Pokeball(Pokeball::SportBall) => &SportBall,
            Item::Pokeball(Pokeball::NetBall) => &NetBall,
            Item::Pokeball(Pokeball::NestBall) => &NestBall,
            Item::Pokeball(Pokeball::RepeatBall) => &RepeatBall,
            Item::Pokeball(Pokeball::TimerBall) => &TimerBall,
            Item::Pokeball(Pokeball::LuxuryBall) => &LuxuryBall,
            Item::Pokeball(Pokeball::PremierBall) => &PremierBall,
            Item::Pokeball(Pokeball::DiveBall) => &DiveBall,
            Item::Pokeball(Pokeball::DuskBall) => &DuskBall,
            Item::Pokeball(Pokeball::HealBall) => &HealBall,
            Item::Pokeball(Pokeball::QuickBall) => &QuickBall,
            Item::Pokeball(Pokeball::CherishBall) => &CherishBall,
            Item::Pokeball(Pokeball::ParkBall) => &ParkBall,
            Item::Pokeball(Pokeball::DreamBall) => &DreamBall,
            Item::Stone(EvolutionStone::FireStone) => &FireStone,
            Item::Stone(EvolutionStone::WaterStone) => &WaterStone,
            Item::Stone(EvolutionStone::ThunderStone) => &ThunderStone,
            Item::Stone(EvolutionStone::LeafStone) => &LeafStone,
            Item::Stone(EvolutionStone::MoonStone) => &MoonStone,
            Item::Stone(EvolutionStone::SunStone) => &SunStone,
            Item::Stone(EvolutionStone::ShinyStone) => &ShinyStone,
            Item::Stone(EvolutionStone::DuskStone) => &DuskStone,
            Item::Stone(EvolutionStone::DawnStone) => &DawnStone,
            Item::Stone(EvolutionStone::IceStone) => &IceStone,
            Item::Incense(Incense::FullIncense) => &FullIncense,
            Item::Incense(Incense::LaxIncense) => &LaxIncense,
            Item::Incense(Incense::LuckIncense) => &LuckIncense,
            Item::Incense(Incense::OddIncense) => &OddIncense,
            Item::Incense(Incense::PureIncense) => &PureIncense,
            Item::Incense(Incense::RockIncense) => &RockIncense,
            Item::Incense(Incense::RoseIncense) => &RoseIncense,
            Item::Incense(Incense::SeaIncense) => &SeaIncense,
            Item::Incense(Incense::WaveIncense) => &WaveIncense,
            Item::EvolutionHeldItem(EvolutionHeldItem::DeepSeaTooth) => &DeepSeaTooth,
            Item::EvolutionHeldItem(EvolutionHeldItem::DeepSeaScale) => &DeepSeaScale,
            Item::EvolutionHeldItem(EvolutionHeldItem::DragonScale) => &DragonScale,
            Item::EvolutionHeldItem(EvolutionHeldItem::DubiousDisk) => &DubiousDisc,
            Item::EvolutionHeldItem(EvolutionHeldItem::Electirizer) => &Electirizer,
            Item::EvolutionHeldItem(EvolutionHeldItem::KingsRock) => &KingsRock,
            Item::EvolutionHeldItem(EvolutionHeldItem::Magmarizer) => &Magmarizer,
            Item::EvolutionHeldItem(EvolutionHeldItem::MetalCoat) => &MetalCoat,
            Item::EvolutionHeldItem(EvolutionHeldItem::OvalStone) => &OvalStone,
            Item::EvolutionHeldItem(EvolutionHeldItem::PrismScale) => &PrismScale,
            Item::EvolutionHeldItem(EvolutionHeldItem::Protector) => &Protector,
            Item::EvolutionHeldItem(EvolutionHeldItem::RazorClaw) => &RazorClaw,
            Item::EvolutionHeldItem(EvolutionHeldItem::RazorFang) => &RazorFang,
            Item::EvolutionHeldItem(EvolutionHeldItem::ReaperCloth) => &ReaperCloth,
            Item::EvolutionHeldItem(EvolutionHeldItem::UpGrade) => &UpGrade,
            Item::Berry(Berry::CheriBerry) => &CheriBerry,
            Item::Berry(Berry::ChestoBerry) => &ChestoBerry,
            Item::Berry(Berry::PechaBerry) => &PechaBerry,
            Item::Berry(Berry::RawstBerry) => &RawstBerry,
            Item::Berry(Berry::AspearBerry) => &AspearBerry,
            Item::Berry(Berry::LeppaBerry) => &LeppaBerry,
            Item::Berry(Berry::OranBerry) => &OranBerry,
            Item::Berry(Berry::PersimBerry) => &PersimBerry,
            Item::Berry(Berry::LumBerry) => &LumBerry,
            Item::Berry(Berry::SitrusBerry) => &SitrusBerry,
            Item::Berry(Berry::FigyBerry) => &FigyBerry,
            Item::Berry(Berry::WikiBerry) => &WikiBerry,
            Item::Berry(Berry::MagoBerry) => &MagoBerry,
            Item::Berry(Berry::AguavBerry) => &AguavBerry,
            Item::Berry(Berry::IapapaBerry) => &IapapaBerry,
            Item::Berry(Berry::RazzBerry) => &RazzBerry,
            Item::Berry(Berry::BlukBerry) => &BlukBerry,
            Item::Berry(Berry::NanabBerry) => &NanabBerry,
            Item::Berry(Berry::WepearBerry) => &WepearBerry,
            Item::Berry(Berry::PinapBerry) => &PinapBerry,
            Item::Berry(Berry::PomegBerry) => &PomegBerry,
            Item::Berry(Berry::KelpsyBerry) => &KelpsyBerry,
            Item::Berry(Berry::QualotBerry) => &QualotBerry,
            Item::Berry(Berry::HondewBerry) => &HondewBerry,
            Item::Berry(Berry::GrepaBerry) => &GrepaBerry,
            Item::Berry(Berry::TamatoBerry) => &TamatoBerry,
            Item::Berry(Berry::CornnBerry) => &CornnBerry,
            Item::Berry(Berry::MagostBerry) => &MagostBerry,
            Item::Berry(Berry::RabutaBerry) => &RabutaBerry,
            Item::Berry(Berry::NomelBerry) => &NomelBerry,
            Item::Berry(Berry::SpelonBerry) => &SpelonBerry,
            Item::Berry(Berry::PamtreBerry) => &PamtreBerry,
            Item::Berry(Berry::WatmelBerry) => &WatmelBerry,
            Item::Berry(Berry::DurinBerry) => &DurinBerry,
            Item::Berry(Berry::BelueBerry) => &BelueBerry,
            Item::Berry(Berry::OccaBerry) => &OccaBerry,
            Item::Berry(Berry::PasshoBerry) => &PasshoBerry,
            Item::Berry(Berry::WacanBerry) => &WacanBerry,
            Item::Berry(Berry::RindoBerry) => &RindoBerry,
            Item::Berry(Berry::YacheBerry) => &YacheBerry,
            Item::Berry(Berry::ChopleBerry) => &ChopleBerry,
            Item::Berry(Berry::KebiaBerry) => &KebiaBerry,
            Item::Berry(Berry::ShucaBerry) => &ShucaBerry,
            Item::Berry(Berry::CobaBerry) => &CobaBerry,
            Item::Berry(Berry::PayapaBerry) => &PayapaBerry,
            Item::Berry(Berry::TangaBerry) => &TangaBerry,
            Item::Berry(Berry::ChartiBerry) => &ChartiBerry,
            Item::Berry(Berry::KasibBerry) => &KasibBerry,
            Item::Berry(Berry::HabanBerry) => &HabanBerry,
            Item::Berry(Berry::ColburBerry) => &ColburBerry,
            Item::Berry(Berry::BabiriBerry) => &BabiriBerry,
            Item::Berry(Berry::ChilanBerry) => &ChilanBerry,
            Item::Berry(Berry::LiechiBerry) => &LiechiBerry,
            Item::Berry(Berry::GanlonBerry) => &GanlonBerry,
            Item::Berry(Berry::SalacBerry) => &SalacBerry,
            Item::Berry(Berry::PetayaBerry) => &PetayaBerry,
            Item::Berry(Berry::ApicotBerry) => &ApicotBerry,
            Item::Berry(Berry::LansatBerry) => &LansatBerry,
            Item::Berry(Berry::StarfBerry) => &StarfBerry,
            Item::Berry(Berry::EnigmaBerry) => &EnigmaBerry,
            Item::Berry(Berry::MicleBerry) => &MicleBerry,
            Item::Berry(Berry::CustapBerry) => &CustapBerry,
            Item::Berry(Berry::JabocaBerry) => &JabocaBerry,
            Item::Berry(Berry::RowapBerry) => &RowapBerry,
            Item::Berry(Berry::RoseliBerry) => &RoseliBerry,
            Item::Berry(Berry::KeeBerry) => &KeeBerry,
            Item::Berry(Berry::MarangaBerry) => &MarangaBerry,
            Item::Mail(Mail::AirMail(_)) => &AirMail,
            Item::Mail(Mail::BloomMail(_)) => &BloomMail,
            Item::Mail(Mail::BrickMail(_)) => &BrickMail,
            Item::Mail(Mail::BubbleMail(_)) => &BubbleMail,
            Item::Mail(Mail::FlameMail(_)) => &FlameMail,
            Item::Mail(Mail::GrassMail(_)) => &GrassMail,
            Item::Mail(Mail::HeartMail(_)) => &HeartMail,
            Item::Mail(Mail::MosaicMail(_)) => &MosaicMail,
            Item::Mail(Mail::SnowMail(_)) => &SnowMail,
            Item::Mail(Mail::SpaceMail(_)) => &SpaceMail,
            Item::Mail(Mail::SteelMail(_)) => &SteelMail,
            Item::Mail(Mail::TunnelMail(_)) => &TunnelMail,
            Item::Potion => &Potion,
            Item::SuperPotion => &SuperPotion,
            Item::HyperPotion => &HyperPotion,
            Item::MaxPotion => &MaxPotion,
            Item::BerryJuice => &BerryJuice,
            Item::EnergyRoot => &EnergyRoot,
            Item::EnergyPowder => &EnergyPowder,
            Item::FreshWater => &FreshWater,
            Item::Lemonade => &Lemonade,
            Item::MoomooMilk => &MoomooMilk,
            Item::RageCandyBar => &RageCandyBar,
            Item::SacredAsh => &SacredAsh,
            Item::ShellBell => &ShellBell,
            Item::SodaPop => &SodaPop,
            Item::SweetHeart => &SweetHeart,
            Item::RevivalHerb => &RevivalHerb,
            Item::Antidote => &Antidote,
            Item::Awakening => &Awakening,
            Item::BurnHeal => &BurnHeal,
            Item::FullHeal => &FullHeal,
            Item::FullRestore => &FullRestore,
            Item::IceHeal => &IceHeal,
            Item::ParalyzeHeal => &ParalyzeHeal,
            Item::Revive => &Revive,
            Item::MaxRevive => &MaxRevive,
            Item::LavaCookie => &LavaCookie,
            Item::MentalHerb => &MentalHerb,
            Item::OldGateau => &OldGateau,
            Item::Casteliacone => &Casteliacone,
            Item::Ether => &Ether,
            Item::MaxEther => &MaxEther,
            Item::Elixir => &Elixir,
            Item::MaxElixir => &MaxElixir,
            Item::PPUp => &PpUp,
            Item::PPMax => &PpMax,
            Item::HPUp => &HpUp,
            Item::Protein => &Protein,
            Item::Iron => &Iron,
            Item::Calcium => &Calcium,
            Item::Zinc => &Zinc,
            Item::Carbos => &Carbos,
            Item::ShockDrive => &ShockDrive,
            Item::BurnDrive => &BurnDrive,
            Item::ChillDrive => &ChillDrive,
            Item::DouseDrive => &DouseDrive,
            Item::PowerAnklet => &PowerAnklet,
            Item::PowerBand => &PowerBand,
            Item::PowerBelt => &PowerBelt,
            Item::PowerBracer => &PowerBracer,
            Item::PowerLens => &PowerLens,
            Item::PowerWeight => &PowerWeight,
            Item::ExpShare => &ExpShare,
            Item::LuckyEgg => &LuckyEgg,
            Item::DracoPlate => &DracoPlate,
            Item::DreadPlate => &DreadPlate,
            Item::EarthPlate => &EarthPlate,
            Item::FistPlate => &FistPlate,
            Item::FlamePlate => &FlamePlate,
            Item::IciclePlate => &IciclePlate,
            Item::InsectPlate => &InsectPlate,
            Item::IronPlate => &IronPlate,
            Item::MeadowPlate => &MeadowPlate,
            Item::MindPlate => &MindPlate,
            Item::PixiePlate => &PixiePlate,
            Item::SkyPlate => &SkyPlate,
            Item::SplashPlate => &SplashPlate,
            Item::SpookyPlate => &SpookyPlate,
            Item::StonePlate => &StonePlate,
            Item::ToxicPlate => &ToxicPlate,
            Item::ZapPlate => &ZapPlate,
            Item::Eviolite => &Eviolite,
            Item::Leek => &Leek,
            Item::LightBall => &LightBall,
            Item::LuckyPunch => &LuckyPunch,
            Item::MetalPowder => &MetalPowder,
            Item::QuickPowder => &QuickPowder,
            Item::SoulDew => &SoulDew,
            Item::ThickClub => &ThickClub,
            Item::BlackBelt => &BlackBelt,
            Item::BlackGlasses => &BlackGlasses,
            Item::Charcoal => &Charcoal,
            Item::DragonFang => &DragonFang,
            Item::HardStone => &HardStone,
            Item::Magnet => &Magnet,
            Item::MetalCoat => &MetalCoat,
            Item::MiracleSeed => &MiracleSeed,
            Item::MysticWater => &MysticWater,
            Item::NeverMeltIce => &NeverMeltIce,
            Item::PoisonBarb => &PoisonBarb,
            Item::SharpBeak => &SharpBeak,
            Item::SilkScarf => &SilkScarf,
            Item::SilverPowder => &SilverPowder,
            Item::SoftSand => &SoftSand,
            Item::SpellTag => &SpellTag,
            Item::TwistedSpoon => &TwistedSpoon,
            Item::AdamantOrb => &AdamantOrb,
            Item::LustrousOrb => &LustrousOrb,
            Item::GriseousOrb => &GriseousOrb,
            Item::BlueScarf => &BlueScarf,
            Item::GreenScarf => &GreenScarf,
            Item::PinkScarf => &PinkScarf,
            Item::RedScarf => &RedScarf,
            Item::YellowScarf => &YellowScarf,
            Item::SootheBell => &SootheBell,
            Item::CleanseTag => &CleanseTag,
            Item::ChoiceBand => &ChoiceBand,
            Item::ChoiceScarf => &ChoiceScarf,
            Item::ChoiceSpecs => &ChoiceSpecs,
            Item::BlackSludge => &BlackSludge,
            Item::LifeOrb => &LifeOrb,
            Item::RockyHelmet => &RockyHelmet,
            Item::StickyBarb => &StickyBarb,
            Item::GripClaw => &GripClaw,
            Item::LightClay => &LightClay,
            Item::TerrainExtender => &TerrainExtender,
            Item::AssaultVest => &AssaultVest,
            Item::FlameOrb => &FlameOrb,
            Item::IronBall => &IronBall,
            Item::LaggingTail => &LaggingTail,
            Item::MachoBrace => &MachoBrace,
            Item::RingTarget => &RingTarget,
            Item::ToxicOrb => &ToxicOrb,
            Item::Leftovers => &Leftovers,
            Item::AbsorbBulb => &AbsorbBulb,
            Item::CellBattery => &CellBattery,
            Item::EjectButton => &EjectButton,
            Item::LuminousMoss => &LuminousMoss,
            Item::Snowball => &Snowball,
            Item::WeaknessPolicy => &WeaknessPolicy,
            Item::WideLens => &WideLens,
            Item::Everstone => &cEverstone,
            Item::TM(_) | Item::HM(_) | Item::KeyItem(_) => panic!("No TM, HM, Key Item data filled in")
        }
    }
}

pub static PokeBall: ItemData = ItemData {
    id: 0,
    cost: 200,
    pocket: Pocket::PokeBalls,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: false,
};
pub static GreatBall: ItemData = ItemData {
    id: 1,
    cost: 600,
    pocket: Pocket::PokeBalls,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: false,
};
pub static UltraBall: ItemData = ItemData {
    id: 2,
    cost: 800,
    pocket: Pocket::PokeBalls,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: false,
};
pub static MasterBall: ItemData = ItemData {
    id: 3,
    cost: 0,
    pocket: Pocket::PokeBalls,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: false,
};
pub static SafariBall: ItemData = ItemData {
    id: 4,
    cost: 0,
    pocket: Pocket::PokeBalls,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: false,
};
pub static FastBall: ItemData = ItemData {
    id: 5,
    cost: 0,
    pocket: Pocket::PokeBalls,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static LevelBall: ItemData = ItemData {
    id: 6,
    cost: 0,
    pocket: Pocket::PokeBalls,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static LureBall: ItemData = ItemData {
    id: 7,
    cost: 0,
    pocket: Pocket::PokeBalls,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static HeavyBall: ItemData = ItemData {
    id: 8,
    cost: 0,
    pocket: Pocket::PokeBalls,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static LoveBall: ItemData = ItemData {
    id: 9,
    cost: 0,
    pocket: Pocket::PokeBalls,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static FriendBall: ItemData = ItemData {
    id: 10,
    cost: 0,
    pocket: Pocket::PokeBalls,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static MoonBall: ItemData = ItemData {
    id: 11,
    cost: 0,
    pocket: Pocket::PokeBalls,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static SportBall: ItemData = ItemData {
    id: 12,
    cost: 300,
    pocket: Pocket::PokeBalls,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static NetBall: ItemData = ItemData {
    id: 13,
    cost: 1000,
    pocket: Pocket::PokeBalls,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: false,
};
pub static NestBall: ItemData = ItemData {
    id: 14,
    cost: 1000,
    pocket: Pocket::PokeBalls,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: false,
};
pub static RepeatBall: ItemData = ItemData {
    id: 15,
    cost: 1000,
    pocket: Pocket::PokeBalls,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: false,
};
pub static TimerBall: ItemData = ItemData {
    id: 16,
    cost: 1000,
    pocket: Pocket::PokeBalls,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: false,
};
pub static LuxuryBall: ItemData = ItemData {
    id: 17,
    cost: 1000,
    pocket: Pocket::PokeBalls,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: false,
};
pub static PremierBall: ItemData = ItemData {
    id: 18,
    cost: 20,
    pocket: Pocket::PokeBalls,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: false,
};
pub static DiveBall: ItemData = ItemData {
    id: 19,
    cost: 1000,
    pocket: Pocket::PokeBalls,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: false,
};
pub static DuskBall: ItemData = ItemData {
    id: 20,
    cost: 1000,
    pocket: Pocket::PokeBalls,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: false,
};
pub static HealBall: ItemData = ItemData {
    id: 21,
    cost: 300,
    pocket: Pocket::PokeBalls,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: false,
};
pub static QuickBall: ItemData = ItemData {
    id: 22,
    cost: 1000,
    pocket: Pocket::PokeBalls,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: false,
};
pub static CherishBall: ItemData = ItemData {
    id: 23,
    cost: 0,
    pocket: Pocket::PokeBalls,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: false,
};
pub static ParkBall: ItemData = ItemData {
    id: 24,
    cost: 0,
    pocket: Pocket::PokeBalls,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static DreamBall: ItemData = ItemData {
    id: 25,
    cost: 0,
    pocket: Pocket::PokeBalls,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static FireStone: ItemData = ItemData {
    id: 26,
    cost: 3000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static WaterStone: ItemData = ItemData {
    id: 27,
    cost: 3000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static ThunderStone: ItemData = ItemData {
    id: 28,
    cost: 3000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static LeafStone: ItemData = ItemData {
    id: 29,
    cost: 3000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static MoonStone: ItemData = ItemData {
    id: 30,
    cost: 3000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static SunStone: ItemData = ItemData {
    id: 31,
    cost: 3000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static ShinyStone: ItemData = ItemData {
    id: 32,
    cost: 3000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static DuskStone: ItemData = ItemData {
    id: 33,
    cost: 3000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static DawnStone: ItemData = ItemData {
    id: 34,
    cost: 3000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static IceStone: ItemData = ItemData {
    id: 35,
    cost: 3000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static FullIncense: ItemData = ItemData {
    id: 36,
    cost: 5000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static LaxIncense: ItemData = ItemData {
    id: 37,
    cost: 5000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static LuckIncense: ItemData = ItemData {
    id: 38,
    cost: 11000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static OddIncense: ItemData = ItemData {
    id: 39,
    cost: 2000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static PureIncense: ItemData = ItemData {
    id: 40,
    cost: 6000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static RockIncense: ItemData = ItemData {
    id: 41,
    cost: 2000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static RoseIncense: ItemData = ItemData {
    id: 42,
    cost: 2000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static SeaIncense: ItemData = ItemData {
    id: 43,
    cost: 2000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static WaveIncense: ItemData = ItemData {
    id: 44,
    cost: 2000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static DeepSeaTooth: ItemData = ItemData {
    id: 45,
    cost: 2000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static DeepSeaScale: ItemData = ItemData {
    id: 46,
    cost: 2000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static DragonScale: ItemData = ItemData {
    id: 47,
    cost: 2000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static DubiousDisc: ItemData = ItemData {
    id: 48,
    cost: 2000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static Electirizer: ItemData = ItemData {
    id: 49,
    cost: 2000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static KingsRock: ItemData = ItemData {
    id: 50,
    cost: 5000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static Magmarizer: ItemData = ItemData {
    id: 51,
    cost: 2000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static MetalCoat: ItemData = ItemData {
    id: 52,
    cost: 2000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static OvalStone: ItemData = ItemData {
    id: 53,
    cost: 2000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static PrismScale: ItemData = ItemData {
    id: 54,
    cost: 2000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static Protector: ItemData = ItemData {
    id: 55,
    cost: 2000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static RazorClaw: ItemData = ItemData {
    id: 56,
    cost: 5000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static RazorFang: ItemData = ItemData {
    id: 57,
    cost: 5000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static ReaperCloth: ItemData = ItemData {
    id: 58,
    cost: 2000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static UpGrade: ItemData = ItemData {
    id: 59,
    cost: 2000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static CheriBerry: ItemData = ItemData {
    id: 60,
    cost: 20,
    pocket: Pocket::Medicine,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static ChestoBerry: ItemData = ItemData {
    id: 61,
    cost: 20,
    pocket: Pocket::Medicine,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static PechaBerry: ItemData = ItemData {
    id: 62,
    cost: 20,
    pocket: Pocket::Medicine,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static RawstBerry: ItemData = ItemData {
    id: 63,
    cost: 20,
    pocket: Pocket::Medicine,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static AspearBerry: ItemData = ItemData {
    id: 64,
    cost: 20,
    pocket: Pocket::Medicine,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static LeppaBerry: ItemData = ItemData {
    id: 65,
    cost: 20,
    pocket: Pocket::Medicine,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static OranBerry: ItemData = ItemData {
    id: 66,
    cost: 20,
    pocket: Pocket::Medicine,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static PersimBerry: ItemData = ItemData {
    id: 67,
    cost: 20,
    pocket: Pocket::Medicine,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static LumBerry: ItemData = ItemData {
    id: 68,
    cost: 20,
    pocket: Pocket::Medicine,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static SitrusBerry: ItemData = ItemData {
    id: 69,
    cost: 20,
    pocket: Pocket::Medicine,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static FigyBerry: ItemData = ItemData {
    id: 70,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static WikiBerry: ItemData = ItemData {
    id: 71,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static MagoBerry: ItemData = ItemData {
    id: 72,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static AguavBerry: ItemData = ItemData {
    id: 73,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static IapapaBerry: ItemData = ItemData {
    id: 74,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static RazzBerry: ItemData = ItemData {
    id: 75,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static BlukBerry: ItemData = ItemData {
    id: 76,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static NanabBerry: ItemData = ItemData {
    id: 77,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static WepearBerry: ItemData = ItemData {
    id: 78,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static PinapBerry: ItemData = ItemData {
    id: 79,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static PomegBerry: ItemData = ItemData {
    id: 80,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static KelpsyBerry: ItemData = ItemData {
    id: 81,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static QualotBerry: ItemData = ItemData {
    id: 82,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static HondewBerry: ItemData = ItemData {
    id: 83,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static GrepaBerry: ItemData = ItemData {
    id: 84,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static TamatoBerry: ItemData = ItemData {
    id: 85,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static CornnBerry: ItemData = ItemData {
    id: 86,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static MagostBerry: ItemData = ItemData {
    id: 87,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static RabutaBerry: ItemData = ItemData {
    id: 88,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static NomelBerry: ItemData = ItemData {
    id: 89,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static SpelonBerry: ItemData = ItemData {
    id: 90,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static PamtreBerry: ItemData = ItemData {
    id: 91,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static WatmelBerry: ItemData = ItemData {
    id: 92,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static DurinBerry: ItemData = ItemData {
    id: 93,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static BelueBerry: ItemData = ItemData {
    id: 94,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static OccaBerry: ItemData = ItemData {
    id: 95,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static PasshoBerry: ItemData = ItemData {
    id: 96,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static WacanBerry: ItemData = ItemData {
    id: 97,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static RindoBerry: ItemData = ItemData {
    id: 98,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static YacheBerry: ItemData = ItemData {
    id: 99,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static ChopleBerry: ItemData = ItemData {
    id: 100,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static KebiaBerry: ItemData = ItemData {
    id: 101,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static ShucaBerry: ItemData = ItemData {
    id: 102,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static CobaBerry: ItemData = ItemData {
    id: 103,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static PayapaBerry: ItemData = ItemData {
    id: 104,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static TangaBerry: ItemData = ItemData {
    id: 105,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static ChartiBerry: ItemData = ItemData {
    id: 106,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static KasibBerry: ItemData = ItemData {
    id: 107,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static HabanBerry: ItemData = ItemData {
    id: 108,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static ColburBerry: ItemData = ItemData {
    id: 109,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static BabiriBerry: ItemData = ItemData {
    id: 110,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static ChilanBerry: ItemData = ItemData {
    id: 111,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static LiechiBerry: ItemData = ItemData {
    id: 112,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static GanlonBerry: ItemData = ItemData {
    id: 113,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static SalacBerry: ItemData = ItemData {
    id: 114,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static PetayaBerry: ItemData = ItemData {
    id: 115,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static ApicotBerry: ItemData = ItemData {
    id: 116,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static LansatBerry: ItemData = ItemData {
    id: 117,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static StarfBerry: ItemData = ItemData {
    id: 118,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static EnigmaBerry: ItemData = ItemData {
    id: 119,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static MicleBerry: ItemData = ItemData {
    id: 120,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static CustapBerry: ItemData = ItemData {
    id: 121,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static JabocaBerry: ItemData = ItemData {
    id: 122,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static RowapBerry: ItemData = ItemData {
    id: 123,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static RoseliBerry: ItemData = ItemData {
    id: 124,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static KeeBerry: ItemData = ItemData {
    id: 125,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static MarangaBerry: ItemData = ItemData {
    id: 126,
    cost: 20,
    pocket: Pocket::Berries,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static AirMail: ItemData = ItemData {
    id: 127,
    cost: 50,
    pocket: Pocket::Mail,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static BloomMail: ItemData = ItemData {
    id: 128,
    cost: 50,
    pocket: Pocket::Mail,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static BrickMail: ItemData = ItemData {
    id: 129,
    cost: 50,
    pocket: Pocket::Mail,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static BubbleMail: ItemData = ItemData {
    id: 130,
    cost: 50,
    pocket: Pocket::Mail,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static FlameMail: ItemData = ItemData {
    id: 131,
    cost: 50,
    pocket: Pocket::Mail,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static GrassMail: ItemData = ItemData {
    id: 132,
    cost: 50,
    pocket: Pocket::Mail,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static HeartMail: ItemData = ItemData {
    id: 133,
    cost: 50,
    pocket: Pocket::Mail,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static MosaicMail: ItemData = ItemData {
    id: 134,
    cost: 50,
    pocket: Pocket::Mail,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static SnowMail: ItemData = ItemData {
    id: 135,
    cost: 50,
    pocket: Pocket::Mail,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static SpaceMail: ItemData = ItemData {
    id: 136,
    cost: 50,
    pocket: Pocket::Mail,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static SteelMail: ItemData = ItemData {
    id: 137,
    cost: 50,
    pocket: Pocket::Mail,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static TunnelMail: ItemData = ItemData {
    id: 138,
    cost: 50,
    pocket: Pocket::Mail,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static Potion: ItemData = ItemData {
    id: 139,
    cost: 200,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static SuperPotion: ItemData = ItemData {
    id: 140,
    cost: 700,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static HyperPotion: ItemData = ItemData {
    id: 141,
    cost: 1500,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static MaxPotion: ItemData = ItemData {
    id: 142,
    cost: 2500,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static BerryJuice: ItemData = ItemData {
    id: 143,
    cost: 200,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static EnergyRoot: ItemData = ItemData {
    id: 144,
    cost: 1200,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static EnergyPowder: ItemData = ItemData {
    id: 145,
    cost: 500,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static FreshWater: ItemData = ItemData {
    id: 146,
    cost: 200,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static Lemonade: ItemData = ItemData {
    id: 147,
    cost: 400,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static MoomooMilk: ItemData = ItemData {
    id: 148,
    cost: 600,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static RageCandyBar: ItemData = ItemData {
    id: 149,
    cost: 350,
    pocket: Pocket::KeyItems,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static SacredAsh: ItemData = ItemData {
    id: 150,
    cost: 50000,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static ShellBell: ItemData = ItemData {
    id: 151,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static SodaPop: ItemData = ItemData {
    id: 152,
    cost: 300,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static SweetHeart: ItemData = ItemData {
    id: 153,
    cost: 3000,
    pocket: Pocket::Medicine,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static RevivalHerb: ItemData = ItemData {
    id: 154,
    cost: 2800,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static Antidote: ItemData = ItemData {
    id: 155,
    cost: 200,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static Awakening: ItemData = ItemData {
    id: 156,
    cost: 100,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static BurnHeal: ItemData = ItemData {
    id: 157,
    cost: 300,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static FullHeal: ItemData = ItemData {
    id: 158,
    cost: 400,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static FullRestore: ItemData = ItemData {
    id: 159,
    cost: 3000,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static IceHeal: ItemData = ItemData {
    id: 160,
    cost: 100,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static ParalyzeHeal: ItemData = ItemData {
    id: 161,
    cost: 300,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static Revive: ItemData = ItemData {
    id: 162,
    cost: 2000,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static MaxRevive: ItemData = ItemData {
    id: 163,
    cost: 4000,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static LavaCookie: ItemData = ItemData {
    id: 164,
    cost: 350,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static MentalHerb: ItemData = ItemData {
    id: 165,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static OldGateau: ItemData = ItemData {
    id: 166,
    cost: 350,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static Casteliacone: ItemData = ItemData {
    id: 167,
    cost: 350,
    pocket: Pocket::Medicine,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static Ether: ItemData = ItemData {
    id: 168,
    cost: 1200,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static MaxEther: ItemData = ItemData {
    id: 169,
    cost: 2000,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static Elixir: ItemData = ItemData {
    id: 170,
    cost: 3000,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static MaxElixir: ItemData = ItemData {
    id: 171,
    cost: 4500,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static PpUp: ItemData = ItemData {
    id: 172,
    cost: 10000,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static PpMax: ItemData = ItemData {
    id: 173,
    cost: 10000,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static HpUp: ItemData = ItemData {
    id: 174,
    cost: 10000,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static Protein: ItemData = ItemData {
    id: 175,
    cost: 10000,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static Iron: ItemData = ItemData {
    id: 176,
    cost: 10000,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static Calcium: ItemData = ItemData {
    id: 177,
    cost: 10000,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static Zinc: ItemData = ItemData {
    id: 178,
    cost: 10000,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static Carbos: ItemData = ItemData {
    id: 179,
    cost: 10000,
    pocket: Pocket::Medicine,
    countable: true,
    consumable: true,
    holdable: true,
    battle_usable: true,
    overworld_usable: true,
};
pub static ShockDrive: ItemData = ItemData {
    id: 180,
    cost: 0,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static BurnDrive: ItemData = ItemData {
    id: 181,
    cost: 0,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static ChillDrive: ItemData = ItemData {
    id: 182,
    cost: 0,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static DouseDrive: ItemData = ItemData {
    id: 183,
    cost: 0,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static PowerAnklet: ItemData = ItemData {
    id: 184,
    cost: 3000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static PowerBand: ItemData = ItemData {
    id: 185,
    cost: 3000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static PowerBelt: ItemData = ItemData {
    id: 186,
    cost: 3000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static PowerBracer: ItemData = ItemData {
    id: 187,
    cost: 3000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static PowerLens: ItemData = ItemData {
    id: 188,
    cost: 3000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static PowerWeight: ItemData = ItemData {
    id: 189,
    cost: 3000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static ExpShare: ItemData = ItemData {
    id: 190,
    cost: 0,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static LuckyEgg: ItemData = ItemData {
    id: 191,
    cost: 10000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static DracoPlate: ItemData = ItemData {
    id: 192,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static DreadPlate: ItemData = ItemData {
    id: 193,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static EarthPlate: ItemData = ItemData {
    id: 194,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static FistPlate: ItemData = ItemData {
    id: 195,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static FlamePlate: ItemData = ItemData {
    id: 196,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static IciclePlate: ItemData = ItemData {
    id: 197,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static InsectPlate: ItemData = ItemData {
    id: 198,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static IronPlate: ItemData = ItemData {
    id: 199,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static MeadowPlate: ItemData = ItemData {
    id: 200,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static MindPlate: ItemData = ItemData {
    id: 201,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static PixiePlate: ItemData = ItemData {
    id: 202,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static SkyPlate: ItemData = ItemData {
    id: 203,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static SplashPlate: ItemData = ItemData {
    id: 204,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static SpookyPlate: ItemData = ItemData {
    id: 205,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static StonePlate: ItemData = ItemData {
    id: 206,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static ToxicPlate: ItemData = ItemData {
    id: 207,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static ZapPlate: ItemData = ItemData {
    id: 208,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static Eviolite: ItemData = ItemData {
    id: 209,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static Leek: ItemData = ItemData {
    id: 210,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static LightBall: ItemData = ItemData {
    id: 211,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static LuckyPunch: ItemData = ItemData {
    id: 212,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static MetalPowder: ItemData = ItemData {
    id: 213,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static QuickPowder: ItemData = ItemData {
    id: 214,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static SoulDew: ItemData = ItemData {
    id: 215,
    cost: 0,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static ThickClub: ItemData = ItemData {
    id: 216,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static BlackBelt: ItemData = ItemData {
    id: 217,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static BlackGlasses: ItemData = ItemData {
    id: 218,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static Charcoal: ItemData = ItemData {
    id: 219,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static DragonFang: ItemData = ItemData {
    id: 220,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static HardStone: ItemData = ItemData {
    id: 221,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static Magnet: ItemData = ItemData {
    id: 222,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static MiracleSeed: ItemData = ItemData {
    id: 224,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static MysticWater: ItemData = ItemData {
    id: 225,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static NeverMeltIce: ItemData = ItemData {
    id: 226,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static PoisonBarb: ItemData = ItemData {
    id: 227,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static SharpBeak: ItemData = ItemData {
    id: 228,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static SilkScarf: ItemData = ItemData {
    id: 229,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static SilverPowder: ItemData = ItemData {
    id: 230,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static SoftSand: ItemData = ItemData {
    id: 231,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static SpellTag: ItemData = ItemData {
    id: 232,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static TwistedSpoon: ItemData = ItemData {
    id: 233,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static AdamantOrb: ItemData = ItemData {
    id: 234,
    cost: 0,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static LustrousOrb: ItemData = ItemData {
    id: 235,
    cost: 0,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static GriseousOrb: ItemData = ItemData {
    id: 236,
    cost: 0,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static BlueScarf: ItemData = ItemData {
    id: 237,
    cost: 100,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static GreenScarf: ItemData = ItemData {
    id: 238,
    cost: 100,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static PinkScarf: ItemData = ItemData {
    id: 239,
    cost: 100,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static RedScarf: ItemData = ItemData {
    id: 240,
    cost: 100,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static YellowScarf: ItemData = ItemData {
    id: 241,
    cost: 100,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static SootheBell: ItemData = ItemData {
    id: 242,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static CleanseTag: ItemData = ItemData {
    id: 243,
    cost: 5000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static ChoiceBand: ItemData = ItemData {
    id: 244,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static ChoiceScarf: ItemData = ItemData {
    id: 245,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static ChoiceSpecs: ItemData = ItemData {
    id: 246,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static BlackSludge: ItemData = ItemData {
    id: 247,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static LifeOrb: ItemData = ItemData {
    id: 248,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static RockyHelmet: ItemData = ItemData {
    id: 249,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static StickyBarb: ItemData = ItemData {
    id: 250,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static GripClaw: ItemData = ItemData {
    id: 251,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static LightClay: ItemData = ItemData {
    id: 252,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static TerrainExtender: ItemData = ItemData {
    id: 253,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static AssaultVest: ItemData = ItemData {
    id: 254,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static FlameOrb: ItemData = ItemData {
    id: 255,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static IronBall: ItemData = ItemData {
    id: 256,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static LaggingTail: ItemData = ItemData {
    id: 257,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static MachoBrace: ItemData = ItemData {
    id: 258,
    cost: 3000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static RingTarget: ItemData = ItemData {
    id: 259,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static ToxicOrb: ItemData = ItemData {
    id: 260,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static Leftovers: ItemData = ItemData {
    id: 261,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static AbsorbBulb: ItemData = ItemData {
    id: 262,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static CellBattery: ItemData = ItemData {
    id: 263,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static EjectButton: ItemData = ItemData {
    id: 264,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static LuminousMoss: ItemData = ItemData {
    id: 265,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static Snowball: ItemData = ItemData {
    id: 266,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static WeaknessPolicy: ItemData = ItemData {
    id: 267,
    cost: 1000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: false,
    battle_usable: false,
    overworld_usable: false,
};
pub static WideLens: ItemData = ItemData {
    id: 268,
    cost: 4000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
pub static cEverstone: ItemData = ItemData {
    id: 269,
    cost: 3000,
    pocket: Pocket::Items,
    countable: false,
    consumable: false,
    holdable: true,
    battle_usable: false,
    overworld_usable: false,
};
//endregion