[package]
name = "glazed_dx"
version = "0.1.0"
authors = ["Justis <lamanna.justis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
simple_logger = "2.1.0"
glazed_core = { path = "../glazed-core" }
glazed_data = { path = "../glazed-data" }
glazed_battle = { path = "../glazed-battle" }
